---
global:
  pattern: rhoai-ray
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  dsc: true
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"

letsencrypt:
  region: ap-southeast-1
  email: chbutler@redhat.com
  server: https://acme-v02.api.letsencrypt.org/directory
