apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: data-connnection-eso
  namespace: science-project
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name:  awss3
    template:
      type: Opaque
      metadata:
        annotations:
          opendatahub.io/connection-type: s3
          openshift.io/display-name: awss3

        labels:
          opendatahub.io/dashboard: "true"
          opendatahub.io/managed: "true"
      data:
        verify_ssl: "false"
        type: s3
        AWS_ACCESS_KEY_ID: >-
          {{ printf "{{ .AWS_ACCESS_KEY_ID | toString }}" }}
        AWS_SECRET_ACCESS_KEY: >-
          {{ printf "{{ .AWS_SECRET_ACCESS_KEY | toString }}" }}
        AWS_DEFAULT_REGION: ""
        AWS_S3_BUCKET: "{{ .Values.dsp.name }}-bucket"
        AWS_S3_ENDPOINT: 	https://s3-openshift-storage.{{ .Values.global.hubClusterDomain }}
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "secret/data/global/s3"
        property: aws_access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "secret/data/global/s3"
        property: aws_secret_access_key