{{ if .Values.clusterGroup.isHubCluster }}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  finalizers:
    - objectbucket.io/finalizer
  name: {{ .Values.dsp.name }}-obc-2
  namespace: {{ .Values.dsp.name }}
spec:
  #generateBucketName: {{ .Values.dsp.name }} 
  bucketName: {{ .Values.dsp.name }}-bucket
  storageClassName: openshift-storage.noobaa.io
  additionalConfig:
    bucketclass: default-bucket
{{ end }}

