{{ if .Values.dsp.pushSecret }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret # Customisable
  namespace: {{ .Values.dsp.name }} # Same of the SecretStores
spec:
  updatePolicy: Replace # Policy to overwrite existing secrets in the provider on sync
  deletionPolicy: Delete # the provider' secret will be deleted if the PushSecret is deleted
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: {{ .Values.secretStore.name }}
      kind: {{ .Values.secretStore.kind }}
  selector:
    secret:
      name: "{{ .Values.dsp.name }}-obc-2" # Source Kubernetes secret to be pushed
  data:
    - match:
        secretKey: AWS_SECRET_ACCESS_KEY # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: "pushsecrets/{{ .Values.dsp.name }}-aws-key"
          property:  AWS_SECRET_ACCESS_KEY # Remote reference (where the secret is going to be pushed
    - match:
        secretKey: AWS_ACCESS_KEY_ID # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: "pushsecrets/{{ .Values.dsp.name }}-aws-key"
          property:  AWS_ACCESS_KEY_ID # Remote reference (where the secret is going to be pushed
{{ end }}