---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/description: "foo"
    openshift.io/display-name: "bar"
  labels:
    opendatahub.io/dashboard: "true"
  name: science-project-pvc
  namespace: science-project
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem