---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: 'foo'
  labels:
    opendatahub.io/dashboard: "true"
  name: {{ .Values.dsp.name}}-book
  namespace: science-project
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem